### ISSUE TITLE
Suggest app name

### ISSUE THREAD

**Issue by PratimaGurav** [PratimaGurav/Team4-May-Hackathon#7]

**Comment by pizzaHunt3r** [comment]
cōnectō: it's Latin for connect and the punctuation has a nice look to it inherently.

**Comment by PratimaGurav** [comment]
connectedocity, connectedsy

**Comment by Amareteklay** [comment]
Connectify

**Comment by StephenB92** [comment]
What about "Rapport"? Since we're including rooms that are shared between people with similar interests

**Comment by PratimaGurav** [comment]
> What about "Rapport"? Since we're including rooms that are shared between people with similar interests

Sorry ths name wasnt available.
